// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFXrpRLV221dhGeg-Mgq1ettM2jBwv--4',
    appId: '1:550815967876:web:6ede96badcd225c67170d1',
    messagingSenderId: '550815967876',
    projectId: 'adminstk-18dd4',
    authDomain: 'adminstk-18dd4.firebaseapp.com',
    storageBucket: 'adminstk-18dd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXuGMFykzoqlsrVkadOrKeK4DUj32B7HI',
    appId: '1:550815967876:android:0afa4c05b646113c7170d1',
    messagingSenderId: '550815967876',
    projectId: 'adminstk-18dd4',
    storageBucket: 'adminstk-18dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOUi2QCcUxTNts1VwNRuxHiwMFt2qLTgA',
    appId: '1:550815967876:ios:f3da6c11a72579d07170d1',
    messagingSenderId: '550815967876',
    projectId: 'adminstk-18dd4',
    storageBucket: 'adminstk-18dd4.firebasestorage.app',
    iosBundleId: 'com.example.adminstk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOUi2QCcUxTNts1VwNRuxHiwMFt2qLTgA',
    appId: '1:550815967876:ios:f3da6c11a72579d07170d1',
    messagingSenderId: '550815967876',
    projectId: 'adminstk-18dd4',
    storageBucket: 'adminstk-18dd4.firebasestorage.app',
    iosBundleId: 'com.example.adminstk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFXrpRLV221dhGeg-Mgq1ettM2jBwv--4',
    appId: '1:550815967876:web:dcabcec30cf799e77170d1',
    messagingSenderId: '550815967876',
    projectId: 'adminstk-18dd4',
    authDomain: 'adminstk-18dd4.firebaseapp.com',
    storageBucket: 'adminstk-18dd4.firebasestorage.app',
  );
}
